### ISSUE TITLE
Repaired potter's wheel not appearing in collection log

### ISSUE THREAD

**Issue by mindfuzz9999** [CarlOmega/examine-log#10]
The repaired potter's wheel at the soul wars island, after being examined, does not lose the asterisk hint. It doesn't appear in the collection log, either.
![image](https://github.com/user-attachments/assets/44a561bd-6766-49fa-acd9-d8e25f94c7ea)
![image](https://github.com/user-attachments/assets/5bf20952-9ffc-4a92-b64d-b967634bd998)
![image](https://github.com/user-attachments/assets/bd9167af-6297-424b-b565-d95530a60277)

**Comment by CarlOmega** [comment]
Got a fix. Opening a PR now.
