### ISSUE TITLE
Collection log pop-ups don't appear

### ISSUE THREAD

**Issue by mike-solomon** [CarlOmega/examine-log#3]
I've tried examining various items such as things on the ground, environment objects, things in my inventory, etc - but I haven't been able to get a collection pop-up for any of these. I do have everything selected - so maybe a conflict with another plugin? Playing on RuneLite through the Jagex launcher. If I can provide further info please let me know. 

![image](https://github.com/user-attachments/assets/3e3a0901-d7e4-4e3b-9bec-ccdff5d795a7)

![image](https://github.com/user-attachments/assets/03dafdce-7e0a-4274-89c9-96554a868bf7)

**Comment by jbcaud** [comment]
It seems like the value used for the pop-up component has changed with new RuneLite versions. I've attached a PR that fixed it on my local development, where the pop-up was not working before. Tagging @CarlOmega to see what he thinks of this.

**Comment by CarlOmega** [comment]
LGTM. Will update the hub.
