### ISSUE TITLE
[SUGGESTION] Show examine texts with different color for items/objects you have NOT yet examined? 

### ISSUE THREAD

**Issue by santzuu** [CarlOmega/examine-log#7]
not really a problem/bug but rather a suggestion - I am not entirely sure how the osrs code works for examines etc. but I was wondering if it would be possible to code it so that items/objects and npc's that you either HAVE examined already or have NOT examined would be different colored? With close to 3k+ examines done its starting to get really confusing which items and objects I have not yet examined and which I have not lol. 

Would be quite helpful if it could be coded to show which are done or which are not done yet. I know this might prove quite difficult since there are objects like iron ore and mithril ore etc. which all produce the exact same examine text but give different "collection slots" also there are some items that have generic same names like "tree" and "flower" and "rock" which produce multiple different examine texts if those can be coded also seperately or not. Thanks a lot anyways and huge thanks that now the plugin works perfectly! My absolutely top 5 plugins all time!

**Comment by CarlOmega** [comment]
Great Idea. It shouldn't be too hard to add. I'll probably just add an asterisk after the 
```
Take Logs
Light Logs
Examine *Logs
Walk Here
Cancel
```

Im working on redesign the interface to be way easier to use. So will try pull the changes in there aswell.

**Comment by CarlOmega** [comment]
Added in this PR: https://github.com/runelite/plugin-hub/pull/6801
I'll close this once it merges thanks for the suggestion and I hope you also enjoy the new UI.

**Comment by CarlOmega** [comment]
Demo if you're interested:

https://github.com/user-attachments/assets/073008b9-3f38-466d-9f48-e000c23190f9

**Comment by CarlOmega** [comment]
UI update is live and the examine hints are too.
