### ISSUE TITLE
Plugin breaks item swaps for Menu Entry Swapper

### ISSUE THREAD

**Issue by Tbird102002** [CarlOmega/examine-log#8]
When this plugin is enabled, ever since a week or so ago, it breaks the ability to change menu options for items held in the inventory in Menu Entry Swapper. 

<3333

**Comment by CarlOmega** [comment]
Fixed in  https://github.com/runelite/plugin-hub/pull/7057
It moves the `*` to the end of the text. There is also a config for hiding examine options once you have found one of them.

**Comment by CarlOmega** [comment]
Should be resolved now.
